version: '3.8'

services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://meu_usuario:123@postgres/meu_banco
    depends_on:
      - postgres
    command: ["./wait-for-it.sh", "postgres:5432", "--", "flask", "run", "--host=0.0.0.0"]

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: meu_usuario
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: meu_banco
    volumes:
      - postgres-volume:/var/lib/postgresql/data

volumes:
  postgres-volume:
