version: '3.8'

services:
  flask_app:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://meu_usuario:123@localhost/meu_banco
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: meu_usuario
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: meu_banco
    volumes:
      - postgres-volume:/var/lib/postgresql/data

volumes:
  postgres-volume:
